### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by woopsn**
@wioux -n10 /one /two /three

### CODE REVIEW

**Comment by wioux** [comment]
Mention:

@wioux -n10 /one /two /three

**Comment by wioux** [comment]
Another mention:

@wioux -n10 /one /two /three

work

**Comment by wioux** [comment]
A third mention:

@wioux -n10 /one /two /three

work

**Comment by wioux** [comment]
Another mention:

@wioux -n10 /one /two /three

work

**Comment by wioux** [comment]
A real mention:

@wioux -n10 /posts

work

**Comment by wioux** [comment]
A real mention:

@wioux -n10 /posts

**Comment by wioux** [comment]
A real mention:

@wioux -n10 /posts

**Comment by wioux** [comment]
A real mention:

@wioux -n10 /posts

**Comment by wioux** [comment]
A real mention:

@wioux -n10 /posts

**Comment by woopsn** [comment]
A real mention:

@wioux -n10 /posts

**Comment by woopsn** [comment]
**/posts**
:white_check_mark: about the same as master (641ms vs 599ms)
:warning: 5500 AR queries were made

[See more details](https://gist.github.com/44e93878149363153786).

**Pull request closed without merging**
